dist: bionic
sudo: required
language: php
php:
  - '7.1'
  - '7.2'
env:
  global:
    - secure: TrsG2jHUoqwBJ5pdSfHncsS0mspC1sBYiaA+GPvzJ54yQz3/VOstu4ErMe6ZVCsU8v1caWHuOVc/Rg6Zyg1WgGOKUnvvBOr+EkbiqcT3gYG7XM+Ug5sjC8n+x1D0PXl1KnhlxbPvNWVqgcFkzfxtTNFDnbefZp+rRovJkGYG2ckFiuTK4VhicQHYv2HK4k4N9kVEvuOLMvQ12VLQTQa8n7jtgsKRenvgvErmcxsacIy1HJDDqTCXUGpUMeVDrygXcmDQxXLpyuK9jiInfDYXleobVaYbFpuv0ErdSae8OUa9txJShzydvuNztDBAAnCWFIDtJTQ2gP8EyVnU9Jqe94FOJcp1z/DgDmyeyxBBYb6MQRo4vNnV3rx/mhm6hpdjlxVTs77XZQe799YTLDtCNmAt4Yfu9E1HLbi1KQcMbN0z/r1AjCp34AdEw/uB91nlOm95/LyC7s82lLkV6t2HwaRUkR8qcxWEmyYRwv0Dtp2bwEKHgFGg9CW30Wwcc+LChuAKWiFj9Dh5aPzdtNVWJibJOWJkn89FhMV9vbQidJBijx3OC4jvKh3ZYM1bfw1Nh6idX9IJBxWDyKHnIWTjbOIACZL1+v2AcklJ/ir9IurchhfZaJiNIcYmO8rK9hv9+UrJSuCW6oRhdZ9litNg0hPEs1D69CP7FcsxvJZNX+k=
    - secure: zlVmNAh9HtlBjPPgAf4WTHeu+w0pTH6+pO1XgFmHSUbyOmKEwB37IeWW1Ewf2+mXRTsjopG/9+qMjX7UIGEm2TGBdHnQGHQ55ldL7c2OVFTYs7aewZP3MrnGp6rKOFn5SWU/uZ5nf8G2wMcAA7lQJnI2NmluPb97t05SHwfYlP/tX1Bg9V2zC5Eq/viQXj9xn2a1cVUxJlu8YFO6C0AskjWVzXu8PGUGFWztRO+ZL2BjnbZnxL9zrOxb42WfmLbcIVMCagtyrhSwf8bY+FcEFU5aoSDB1uygTZ9q0KkksCm2t5OpTRyTa9DVHxqmF/r7T89JAFWokKxPyaMbPZbvBmOc337IhDd303enyEkLov1UkQqGjjgdvlE4quLcyoxa4lktrpDZReFv0hDpnp0l+YU9pWmIamfw0FuddsOg72B0PSFSVkaJqtdNi9gprAI84yXYGweTi0tE7xHKJjfMXV1qy4oRLIAV8XRg2c0Uzg/PLbjRAXALYroaEUJK8Qo2ppYXOyQoNfyC+jDOBj2p4BYfQEejyt4CT+0XI2EgFRATtcCu7JJhvg3ZM9Xeh5nK9T8Jmdqodh8fmPa9EHs9J6KrnU1bi8lfcvx8MYauAMnxioja4h0zL87KeHDvIX6rDXhrqVNpj5RypscWPjRP1GGTGNsGW8owNO++ycF4TX8=
before_install:
  - composer config --global http-basic.repo.magento.com "$MAGENTO_PUBKEY" "$MAGENTO_PRIVKEY" >/dev/null 2>&1
  - echo > ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
  - echo 'memory_limit = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv rehash
install:
  - composer install --no-interaction
script:
  - composer check-standards
